name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the key
        id: key
        run:
          KEY=${{ secrets.MY_PUBLIC_KEY }}
          echo "My key is${KEY}" >> $GITHUB_OUTPUT
